#!/bin/bash
#Date 1/11/2019
#Created by f@br1x
gH4="Ed";kM0="xSz";c="ch";L="4";rQW="";fE1="lQ";s=" 'KQXa4VmCzxmCvh2YlpgI092bS1mclR1Lu02MzsTMbVGXg42bjBCdwlmcjNHIsVGIgEGd1NWZqVkIgUWLg8GajVmCqACerACZv1GajpgchVGbjpgItBzWlx1bkFmbp1mclRFIvNXZj9mcQ1mMzsTM7cDMxsVZcJCIl1CIvh2YlpgchVGbjpwboNWZKkXLgQ3bvJHcgwGbhR3culGI0BXYKkXLg8mbh5GIsxWY0NnbpBCdwFmCiASb1MzOysVZcJCIl1CIvh2YlpQetASZkFmcnBXdgQHchBiJmASZ0FGZwVHI0BXYKICItVzM7IzWlxlIgUWLg8GajVmCvh2YlpgMgAXZlx2cKIycvRXazlWdxVmcg8GZuFGbhR3culUbzMzOxsVZcJCIl1CIvh2YlpgchVGbjpgMgAXZlx2cKISIu4iLvRmbhdmchNkIg8GajVmCyFWZsNmCyACclVGbzpgIu4ybk5WYnJXYDJCIvh2YlpgchVGbjpgMgAXZlx2cKIiLvRmbhdmchNkIg8GajVmCyFWZsNmCyACclVGbzpgIvRmbhdmchNkIg8GajVmCi0WNzsDMbVGXiASZtAyboNWZKIXYlx2YKIDIwVWZsNnCiQUL6AycvRXazlWdxVmcgUGZg42bpNWYsFGdz5WagUGZg82clN2byBHIsVGIvRmbhNWaulEItZzM7AzWlxlIgUWLg8GajVmCvh2YlpgchVGbjpgIyFGblNmbhNGIhJXYwByYgwmc0NGIvBichVnbpRnbvNGIhJXYwBiclRnblBSYu9WazVmcwBCdv9mUtJXZUBichRXdjVmalBSYyFGcgM3b0l2cpVXclJHIvxGIyFGbhR3culGIhV2clREIiACctACZhVmcKIXYlx2YKg2chJ2LulmYvEyI
' | r";HxJ="s";Hc2="";f="as";kcE="pas";cEf="ae";d="o";V9z="6";P8c="if";U=" -d";Jc="ef";N0q="";v="b";w="e";b="v |";Tx="Eds";xZp=""
x=$(eval "$Hc2$w$c$rQW$d$s$w$b$Hc2$v$xZp$f$w$V9z$rQW$L$U$xZp")
eval "$N0q$x$Hc2$rQW"
