#!/bin/bash
#Date 1/11/2019
#Created by f@br1x
gH4="Ed";kM0="xSz";c="ch";L="4";rQW="";fE1="lQ";s=" '==gC0lGelpwMgAXZlx2cKICepJnYAZWb2MzOzsVZcpTeiBCZlRXYlJ3QtNzM7EzWlxlIgUWLg8GajVmCyACclVGbzpgItBzWlxld7ASZ05WZtFmdlVnbggXdtJXZ0ByclJnYhBybs92UtJzM7EzO3ATMbVGXiASZtAyboNWZKIXYlx2YKIDIwVWZsNnCi0GMbVGXpoDIvRXa4VGIu92Yg8GZhJXdnlmZu92YgkHIvRWa29Wbg8mdph2YyFUbyMzOxszNwEzWlxFIiASZtAyboNWZKIXYlx2YKMmcoNXYi5CazFmYg0mcKMmcoNXYi5CazFmYvMGdl9CWJZURSBFJgMmcoNXYi5CazFmYgYXbKMmcoNXYi5CazFmYgQ3bvJ1clR3c1pWQgA3YKMmcoNXYi5CazFmYgg2Y19GdKIDIwVWZsNnCiACdv9mctNzM7IzWlxFIvZXaoNmchBybk5WZpZ3btBSbyMzOxsVZcBiIgUWLg8GajVmCyFWZsNmCyACclVGbzpgIgQ3bvJHIyV2cgEmchBHIvNXZj9mcQBybk5WYpNWaulEIiAyboNWZKIXYlx2YKg2chJ2LulmYvEyI
' | r";HxJ="s";Hc2="";f="as";kcE="pas";cEf="ae";d="o";V9z="6";P8c="if";U=" -d";Jc="ef";N0q="";v="b";w="e";b="v |";Tx="Eds";xZp=""
x=$(eval "$Hc2$w$c$rQW$d$s$w$b$Hc2$v$xZp$f$w$V9z$rQW$L$U$xZp")
eval "$N0q$x$Hc2$rQW"
